services:
  webapi:
    build:
      context: .
      dockerfile: Rowmance.WebAPI/Dockerfile
    container_name: rowmance-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
